### ISSUE TITLE
Trim Problem

### ISSUE THREAD

**Issue by ghost** [otacke/yalw#3]
Hey Buddy, there is a little problem.

> Fatal error: Can't use function return value in write context in [...]/wp-content/plugins/yalw/handlers.php on line 327

Made a little workaround by storing trims return value in a separete variable. Maybe you have a better solution.

yalw/handlers.php:325

```
     if ( ! empty ( $options ) ) {
         $tmp = trim( $options['code_reset_email_text'] );
         if ( ! empty ( $tmp ) ) {
             $message = $options['code_reset_email_text'];

```

**Comment by otacke** [comment]
Thanks! In what context did the problem occur? I never stumbled across it. Do you mind filing in a pull request so I can give you proper credit?

**Comment by otacke** [comment]
I digged into this. It seems that [before PHP 5.5 `empty` cannot handle anything but variables](http://php.net/manual/en/function.empty.php). Since you're still using PHP 5.4.16 on your system, you found the problem. Your solution is fine, and alternatively you could use

```
if ( ! empty ( trim( $options['code_reset_email_text'] ) == false ) ) {
    $message = $options['code_reset_email_text'];
}
```

Still, I'd like to include the fix via a pull request to give you proper credit. If you prefer me to fix it directly, just drop me a note.

**Comment by ghost** [comment]
I got this right after enabling the plugin.cMight be a problem of the old php version we're using.

> PHP 5.4.16 (cli) (built: Aug 11 2016 21:24:59)

**Comment by otacke** [comment]
I beat you by five minutes ;-)

**Comment by otacke** [comment]
I'll accept your pull request, check the code for similar pitfalls, and prepare an update for the Wordpress repository tonight. Thanks for your contribution!
